### ISSUE TITLE
[Installation manual] Howto receive the hardware requirements for the CSP installation?

### ISSUE THREAD

**Issue by rommelfs** [melicertes/csp#11]
1.1. You received the hardware requirements for the CSP installation

**Comment by thanosa75** [comment]
H/W requirements are part of the registration process. Various options exist, but for a full blown CSP installation you should be looking at:
* ESXi hypervisor (free to use license by VMware)
* 16 vCPUs at 2.6GHz or better, Xeon class
* 48GB RAM
* SSD class storage for at least 800GB (1st tier) and possibly more (2nd tier) and backups 

Note that due to modularity of the system, given that various components can be made optional, possible lowest system spec could possibly fit in ~16GB or less. Ofc, depending on actual traffic (e.g. MiSP events / distribution / RT tickets / IntelMQ usage) the numbers can be substantially bigger, and you (or your system administrator) need to carefully plan ahead. 

A calculator for MiSP can be found here: https://www.misp-project.org/MISP-sizer/
Other projects may or may not have such calculators, and ofc, YMMV.
