### ISSUE TITLE
Connection testing

### ISSUE THREAD

**Issue by sim0nx** [melicertes/csp#32]
Hi,

Could you please not try to connect to google.com:443 for "internet connectivity" testing ?
That seems to be pretty absurd for a controlled production environment, even more as the node already requires connectivity to the central.
Checking for connectivity to the central should be enough.

**Comment by thanosa75** [comment]
Comment understood and under consideration - address was chosen initially but already we have a set of various services (e.g STUN service) that we need to have accessibility to, global DNS, etc. The actual connections shall be enumerated (in the installer logs) and google.com:443 <http://google.com:443/> shall be removed.

Central is indeed a must but also -for the time being- access to Docker Hub.

**Comment by sim0nx** [comment]
Good that google.com checking will be removed.

STUN should be hosted by those hosting the CENTRAL.
Global DNS? You should use was is locally available, not some random open resolver.

Docker Hub access is not documented, neither is DNS, STUN, ....
It seems that you expect people to run this VM with any/any access ?

**Comment by wagner-certat** [comment]
Do not only check if the connection to the central node works, but also to the update server(s) of Alpine Linux!

```
apk update
apk upgrade
```
Otherwise you end up with an outdated system very fast.

**Comment by wagner-certat** [comment]
>  It seems that you expect people to run this VM with any/any access ?

I currently have an open question with trust-central about firewall rules too (which are still badly/not described in the documentation). As far as I *currently* know 443/tcp outgoing to ANY is the recommendation (which prevents alpine updates...).

**Comment by sim0nx** [comment]
Thanks for the hint @wagner-certat  .   443/tcp to any? lol, not doable.
Where do I set proxy settings and where do I get a list of http/https destinations that should be enabled @thanosa75 ?

**Comment by wagner-certat** [comment]
> Thanks for the hint @wagner-certat . 443/tcp to any? lol, not doable.

According to an answer "only during the install check". So firewall rules for setup and afterwards differ :/

**Comment by Rafiot** [comment]
Is there any team using the soft in production at this point? That would probably be the most reliable way to figure that out.

**Comment by sim0nx** [comment]
Not yet. But I guess it would be a better starter to get the documentation completed / fixed.

**Comment by Rafiot** [comment]
That would be optimal, but that only works if the developers can/want to answer our questions. Otherwise, we will need to figure it out by ourselves.

**Comment by thanosa75** [comment]
@Rafiot please do not assume that developers do not want to answer questions. We do have also other tasks. 

> > It seems that you expect people to run this VM with any/any access ?

No this is not the case.

> I currently have an open question with trust-central about firewall rules too (which are still badly/not  described in the documentation). As far as I currently know 443/tcp outgoing to ANY is the recommendation (which prevents alpine updates...).

This is not a recommendation; please do not assume.

Documentation will be updated with _minimum_ connectivity requirements. Bear in mind that the network administrator is expected to enforce own system policy. CSP cannot enforce or restrict this; your net-admin may choose to keep connectivity closed. Even for CSP-2-CSP communication, a list of approved IP addresses is maintained centrally, and if CSIRTs choose to include parties in their LTC to communicate, they should add in their firewall whitelists the relevant IP addresses. Now, choosing to use e.g VC bridge, will require e.g 10000/udp (media) - otherwise it will not work. Other integrated apps may have additional requirements.

Hope this clears it a bit.

**Comment by iglocska** [comment]
Just to skip the wall of text in this thread, so is there a definitive list of ports to open?
