### ISSUE TITLE
Module installation order

### ISSUE THREAD

**Issue by iglocska** [melicertes/csp#38]
The module installation screen gives you the wrong impression that you can pick and choose the modules you would like to install. In reality some modules depend on the installation of other modules.

There is no guidance on which module depends on which other module and the current installation procedure is highly reminiscent of the famous "Dinky Island Woods" in Monkey Island 2.

**Comment by thanosa75** [comment]
The reference to MI2 is not understood. However, there are various mentions in the installation guide, e.g 

- (guide 4.0.6) page 30:
"All available updates should be downloaded reaching the stage where all images are available for installation"
- (guide 4.0.6) page 31:
"After downloading all the updates, the components can be installed. By clicking the green Install icon for each image, the user must install ALL available images, by consecutively clicking the install buttons, for the system to properly function"

There is no guidance because all modules are to be downloaded and installed.

**Comment by iglocska** [comment]
That is weird, during the training we were told that the set of modules to be downloaded and installed is up to the individual CSIRT, meaning if someone doesn't want to use Jitsi for example, they could opt out. Did this change recently?

**Comment by thanosa75** [comment]
The set of modules to be downloaded and installed is up to individual CSIRT, and the 'caretaker' assigns them to the CSIRT. However, according to installation manual, all updates (agreed with CSIRT) are to be downloaded and installed. In other words, if your caretaker does not assign something, you will not see it. There is no confusion or choice, it has been done beforehands.
